### ISSUE TITLE
getting invalid character error will running kubesec-scan 

### ISSUE THREAD

**Issue by jainpratik163** [controlplaneio/kubectl-kubesec#120]
i am trying to run below command  and getting below error

 `k kubesec-scan -n kube-system deployment coredns`

**scanning deployment coredns in namespace kube-system
invalid character '<' looking for beginning of value**

And --kubeconfig is not supported?

**Comment by ledroide** [comment]
Same issue here.
```bash
$ kubectl kubesec-scan version
2.0.0

$ kubectl kubesec-scan -n kube-system deployment metrics-server
scanning deployment metrics-server in namespace kube-system
invalid character '<' looking for beginning of value
```

**Comment by Chupa1230** [comment]
I am having the same issue.

**Comment by spiarh** [comment]
There is a PR open to fix that if you want to give it a try. We'll push a couple of updates in the coming weeks.

**Comment by PePTojr** [comment]
No resolve, yet?
$ kubectl kubesec-scan version
2.0.0

$ kubectl kubesec-scan -n kube-system deployment metrics-server
scanning deployment metrics-server in namespace kube-system
invalid character '<' looking for beginning of value

**Comment by spiarh** [comment]
@PePTojr This is not yet fixed, we're still figuring out a few things about access control on the github repositories in order to move forward with the fixes coming in. Stay tuned.

**Comment by ledroide** [comment]
Maybe I have missed something : why had this issue been closed ?
