### ISSUE TITLE
Invalid character < error while scanning resources

### ISSUE THREAD

**Issue by Allure996** [controlplaneio/kubectl-kubesec#135]
Hi! I've recently downloaded kubesec as a kubectl plugin with krew.
When I try to scan any resource, I always recieve the error:

`invalid character '<' looking for beginning of value`

I know this is something related to Golang unmarshalling, but how can I debug where this error fits with my k8s manifests?
Thank you for in advance.

**Comment by 06kellyjac** [comment]
#120 can you try using master to see if it's resolved?
We'll tag a new release soon

**Comment by Allure996** [comment]
Hi, I'm using it with krew, is there any way to make it download kubesec specifying a branch?
Or did you mean to run it as a binary?

**Comment by 06kellyjac** [comment]
pretty sure krew can't install arbitrary versions

cloning the repo and running `go build` at the root will give you `kubectl-kubesec`

replace any `kubectl kubesec-scan xyz` with `./kubectl-kubesec xyz`
