### ISSUE TITLE
[krew] Distribute with license

### ISSUE THREAD

**Issue by corneliusweig** [controlplaneio/kubectl-kubesec#22]
:wave: Hello, maintainer of the kubectl plugin manager [krew](https://github.com/kubernetes-sigs/krew) here.

Thank you for your commitment to open source by making this plugin available via `krew`!

Krew wants to give credit where credit is due by installing the proper license file for the plugins it distributes. However, your plugin was found to not contain any license file. We wanted to remind you that if you're using a license such as Apache 2.0, you should be bundling your LICENSE file with your plugin’s distributions.

What do you have to do?

* Please ensure your GitHub repository has a license file.
* Make sure your archive file (.tar.gz or .zip) contains the license file.
* Please submit a pull-request to [krew-index](https://github.com/kubernetes-sigs/krew-index) and update the `files:` section to copy the file to the installation directory. Have a look at this PR for an example: [https://github.com/kubernetes-sigs/krew-index/pull/314/files](https://github.com/kubernetes-sigs/krew-index/pull/314/files)

If you need further assistance, don't hesitate to ask for help.

**Comment by ahmetb** [comment]
Ping.

**Comment by sublimino** [comment]
> Please ensure your GitHub repository has a license file.

Confirmed

> Make sure your archive file (.tar.gz or .zip) contains the license file.

It does not. @stefanprodan when I try to use `goreleaser`:
```bash
$ goreleaser --version

goreleaser version 0.133.0
commit: 83e401cfa52ba0f5ad75a6116108cdbe587bbb01
built at: 2020-05-03T18:21:26Z
built by: goreleaser

$ goreleaser
...
line 10: field archive not found in type config.Project
```

Is this still the recommended approach @stefanprodan, or should I migrate to something a bit more like https://github.com/fluxcd/flux/blob/master/Makefile#L42-L52?

> Please submit a pull-request to krew-index and update the files: section to copy the file to the installation directory

When the LICENSE file is in the release tarball the existing code at https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/kubesec-scan.yaml#L20-L21 looks like it should work.

**Comment by stefanprodan** [comment]
The goreleaser config format changed, it’s archives now instead of archive.
