### ISSUE TITLE
This plugin does not return any result

### ISSUE THREAD

**Issue by piyush-saurabh** [controlplaneio/kubectl-kubesec#26]
I keep on getting the below error even if the resource exists on k8 cluster. This is true for all the deployments.

`scanning deployment kubernetes-dashboard in namespace kube-system
the server could not find the requested resource`

Below are the details of the client and server
`Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by christianhxc** [comment]
I'm having the same problem, when I install the plugin, it's saying that the resource is not found

**Comment by si458** [comment]
it an incompatibility error with k8s clusters after 1.16 https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
it appears to be making a request to
`https://yourserver:6443/apis/apps/v1beta2/namespaces/testnamespace/deployments/testdeployment`
**v1beta2** was removed in the k8s 1.16 release
