### ISSUE TITLE
Feature request: Support of helm charts STDIN

### ISSUE THREAD

**Issue by sTb1337** [controlplaneio/kubectl-kubesec#53]
Hello team,

thanks a lot for this great tool. I would like to use this within my CD pipeline to scan complete helm charts.

Therefore I would love to see an support for inputing helm charts like kubeval is doing (see https://www.kubeval.com/#stdin & https://www.kubeval.com/#helm)

Thanks a lot,

kind regards,
Steffen

**Comment by 06kellyjac** [comment]
You can pipe into kubesec and you can easily scan helm resources if you utilize stdin and helm's template feature. (I would also advise you use kubesec directly rather than the kubectl plugin in your CI)

https://github.com/controlplaneio/kubesec/issues/142#issuecomment-763464338

I'll need to look into how kubeval specifically deals with helm variables, but generally we don't want to integrate support for specific deployment tools.
In standard unix style we'd much prefer kubesec stick to analyzing the kubernetes resources, any templating via helm, kustomize, etc, can easily be piped in resulting in support for any template/deployment tool that can output yaml.

**Comment by sTb1337** [comment]
Hello 06kellyjac,

thank you for your answer. 

If not already present, it would be very great to have the helm feature in the following way:
1. use "helm template my-release bitnami/metrics-server | kubesec scan /dev/stdin"
2. kubesec is doing its black magic and print out its result with the additional information like "# Source: chart/templates/frontend.yaml"

So you don't need to implement/use any helm related functionality regarding variables and stuff, just parse from STDIN the path to the helm file in which kubesec found issues.

Is there an difference between kubectl plugin and kubesec directly? 

I will install kubesec directly via (https://github.com/controlplaneio/kubesec#download-kubesec) and use it in this way "helm template my-release bitnami/metrics-server | kubesec scan /dev/stdin".

If this works, I will close my feature request.

Thanks a lot,

kind regards,

Steffen

**Comment by 06kellyjac** [comment]
The `#source: chart/templates` stuff is just the output from helm template:


```
helm template my-release bitnami/metrics-server
---
# Source: metrics-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-release-metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    helm.sh/chart: metrics-server-5.3.4
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
---
# Source: metrics-server/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:my-release-metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
# ... I've cut the rest off to keep this short ...
```

Piping in to kubesec either use `-` or `/dev/stdin` to denote you want it to read from stdin, works just fine.

```
helm template my-release bitnami/metrics-server | kubesec scan -
[
  {
    "object": "ServiceAccount/my-release-metrics-server.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "ClusterRole/system:my-release-metrics-server.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "ClusterRole/system:my-release-metrics-server-aggregated-reader.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "ClusterRoleBinding/my-release-metrics-server:system:auth-delegator.kube-system",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "ClusterRoleBinding/system:my-release-metrics-server.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "RoleBinding/my-release-metrics-server-auth-reader.kube-system",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "Service/my-release-metrics-server.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "This resource kind is not supported by kubesec",
    "score": 0,
    "scoring": {}
  },
  {
    "object": "Deployment/my-release-metrics-server.default",
    "valid": true,
    "fileName": "STDIN",
    "message": "Passed with a score of 3 points",
    "score": 3,
    "scoring": {
      "passed": [
        {
          "id": "ServiceAccountName",
          "selector": ".spec .serviceAccountName",
          "reason": "Service accounts restrict Kubernetes API access and should be configured with least privilege",
          "points": 3
        }
      ],
      "advise": [
        {
          "id": "ApparmorAny",
          "selector": ".metadata .annotations .\"container.apparmor.security.beta.kubernetes.io/nginx\"",
          "reason": "Well defined AppArmor policies may provide greater protection from unknown threats. WARNING: NOT PRODUCTION READY",
          "points": 3
        },
        {
          "id": "SeccompAny",
          "selector": ".metadata .annotations .\"container.seccomp.security.alpha.kubernetes.io/pod\"",
          "reason": "Seccomp profiles set minimum privilege and secure against unknown threats",
          "points": 1
        },
        {
          "id": "LimitsCPU",
          "selector": "containers[] .resources .limits .cpu",
          "reason": "Enforcing CPU limits prevents DOS via resource exhaustion",
          "points": 1
        },
        {
          "id": "LimitsMemory",
          "selector": "containers[] .resources .limits .memory",
          "reason": "Enforcing memory limits prevents DOS via resource exhaustion",
          "points": 1
        },
        {
          "id": "RequestsCPU",
          "selector": "containers[] .resources .requests .cpu",
          "reason": "Enforcing CPU requests aids a fair balancing of resources across the cluster",
          "points": 1
        },
        {
          "id": "RequestsMemory",
          "selector": "containers[] .resources .requests .memory",
          "reason": "Enforcing memory requests aids a fair balancing of resources across the cluster",
          "points": 1
        },
        {
          "id": "CapDropAny",
          "selector": "containers[] .securityContext .capabilities .drop",
          "reason": "Reducing kernel capabilities available to a container limits its attack surface",
          "points": 1
        },
        {
          "id": "CapDropAll",
          "selector": "containers[] .securityContext .capabilities .drop | index(\"ALL\")",
          "reason": "Drop all capabilities and add only those required to reduce syscall attack surface",
          "points": 1
        },
        {
          "id": "ReadOnlyRootFilesystem",
          "selector": "containers[] .securityContext .readOnlyRootFilesystem == true",
          "reason": "An immutable root filesystem can prevent malicious binaries being added to PATH and increase attack cost",
          "points": 1
        },
        {
          "id": "RunAsNonRoot",
          "selector": "containers[] .securityContext .runAsNonRoot == true",
          "reason": "Force the running image to run as a non-root user to ensure least privilege",
          "points": 1
        },
        {
          "id": "RunAsUser",
          "selector": "containers[] .securityContext .runAsUser -gt 10000",
          "reason": "Run as a high-UID user to avoid conflicts with the host's user table",
          "points": 1
        }
      ]
    }
  }
]
```

---

I believe the kubesec kubectl plugin is designed specifically to scan existing pods etc in the cluster by pulling out their yaml and scanning that (similar to `kubectl get pod bob -o yaml | kubesec scan -`)

It also has a more friendly output fitting with end-user use



kubesec itself is the tool at the core of it and outputs json by default, you can then parse the JSON to check if the output meets your requirements e.g. a score > 0, or criticals is empty etc
You can define and check these requirements either using some simple JSON parsing with `jq` and bash to check the values, or you could feed it into OPA and write rego polices.

Up to you

**Comment by sTb1337** [comment]
Thanks again for this detailed answer.

I got everything running and integrated into the CD pipeline on my side. 

It would be very very comfortable to have an additional item on the level of "object": "Deployment/my-release-metrics-server.default", like: "file": "chart/templates/frontend.yaml", which is been parsed from "helm template....".

But I can fully understand you, if you don't want to integrate such helm specific feature.

If needed I will parse the json with "jq" as you suggested to minimize the CD pipeline protocol output.

Kind regards
