### ISSUE TITLE
Add feature to scan yaml instead of already created API objects

### ISSUE THREAD

**Issue by tuxmea** [controlplaneio/kubectl-kubesec#8]
At the moment we can only scan existing objects.
Can we have the possibility to scan yaml file prior creating the objects?

**Comment by rudolphjacksonm** [comment]
Hi @tuxmea --I'd use something like [kube-score](https://github.com/zegl/kube-score) for scanning yaml files.

**Comment by sublimino** [comment]
https://kubesec.io V2 will scan YAML on the CLI and as a web server. It's not yet integrated with this plugin, but can run standalone or hosted and I'll update here when the plugin is updated. Or help welcome if anybody would like to patch it in 🙏

**Comment by spiarh** [comment]
`kubectl-kubesec` relies on `kubesec` under the hood which does exactly what you are looking for https://github.com/controlplaneio/kubesec :wink: 

Otherwise, the Kubesec v2 API is still an option: https://github.com/controlplaneio/kubesec#kubesec-as-a-service
